/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PayList: typeof import('./src/components/pay-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svg-icon.vue')['default']
    TheContent: typeof import('./src/components/layouts/TheContent.vue')['default']
    TheFooter: typeof import('./src/components/layouts/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/layouts/TheHeader.vue')['default']
  }
}
